### ISSUE TITLE
Two theme-color tags with different media and content

### ISSUE THREAD

**Issue by yagee** [ryan-voitiskis/astro-helmet#1]
Hi! Thanks for great plugin!

I have an issue with this code:
```js
const headItems = {
  meta: [
    {
      name: 'theme-color',
      media: '(prefers-color: scheme: light)',
      content: 'cyan',
    },
    {
      name: 'theme-color',
      media: '(prefers-color: scheme: dark)',
      content: 'black',
    },
  ],
};
```
I need two meta tags with "theme-color", but deduplication remove the second one.

This is an example from MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
```html
<meta name="theme-color" media="(prefers-color-scheme: light)" content="cyan" />
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="black" />
```

Any solutions or workarounds to achieve this result?

Thanks!

**Comment by ryan-voitiskis** [comment]
Thank you for the feedback. The issue can be fixed by not deduping when the media attribute does not match - I will publish a fix for this tonight with a test using the example you've provided.

I am also contemplating a excludeFromDedupe (or similar) array in the options. Please let me know if you have any thoughts on that.
